### ISSUE TITLE
Config folder

### ISSUE THREAD

**Issue by AlexDCryptoC** [CelsiusNetwork/celsius-app#18]
Hi there,

Could you please help me with the config folder for dev ? 

Thank you!

**Comment by StefanBurscher** [comment]
Hello Alex,

Can you please provide us your email. Just to be clear, we can't give you any keys, but the structure of app.json, so you have to fill it out with your own key.

**Comment by AlexDCryptoC** [comment]
alex@dcipher.io and thank you very much!
